<?php

/**
 * @file
 * Contains arabic_php.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function arabic_php_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the arabic_php module.
    case 'help.page.arabic_php':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}





/**
 * @file
 * Contains hook implementations for the Text On Image Ar module.
 */

/**
 * Implements hook_image_effects_text_overlay_text_alter().
 */
function arabic_php_image_effects_text_overlay_text_alter(&$text, ConfigurableImageEffectBase $image_effect) {
  // Skip if the effect is not TextOverlayImageEffect or an alternative
  // implementation.
  if ($image_effect->getPluginId() !== "image_effects_text_overlay") {
    return;
  }
  $text = 'my altered text';
}
