<?php

/**
 * @file
 * Contains arabic_php.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function arabic_php_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the arabic_php module.
    case 'help.page.arabic_php':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
